#!/usr/bin/perl
use strict;
use warnings;
use IO::File;
use Data::Dumper;
use YAML qw/LoadFile/;

use Text::CSV;

my @a;

my $datafilename = shift @ARGV;

my $fh = IO::File->new($datafilename);

my $out = IO::Handle->new();
$out->fdopen(fileno(STDOUT),"w");

my $csv = Text::CSV->new;
my $map = {};
while (<$fh>) {
  $csv->parse($_);
  my ($file, $page, $x, $y, $text, $field_name, $separator) = my @row = $csv->fields;
  push @{$map->{$file}{$page}{$field_name}}, [@row];
}

foreach my $file (keys %{$map}) {
  foreach my $page (keys %{$map->{$file}}) {
    foreach my $field_name (keys %{$map->{$file}{$page}}) {
      my $rows = $map->{$file}{$page}{$field_name};
      my $value = join $rows->[0][6], map { $_->[4] } sort { $b->[3] <=> $a->[3] unless $a->[2] <=> $b->[2] } @{$rows};
      $csv->print($out, [$file, $page, $field_name, $value]);
      $out->print("\n");
    }
  }
}

